version: '3.2'
name: alpa-test
services:
  postgres:
    container_name: postgres
    build:
      dockerfile: postgres/Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      PGDATA: ${PGDATA:-/data/postgres}
    volumes:
      - postgres_vol:${PGDATA:-/data/postgres}
    ports:
      - '${DB_PORT:-5432}:5432'
    restart: unless-stopped

  nodejs:
    container_name: nodejs
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: ../.env
    ports:
      - '$API_PORT:$API_PORT'
    volumes:
      - ../src:/app/src
volumes:
  postgres_vol:
  node_modules:
